### ISSUE TITLE
Show link to the homepage on https://rubygems.org

### ISSUE THREAD

**Issue by v-kolesnikov** [red-data-tools/charty#30]
It looks strange that rubygems.org does not show homepage link:

https://github.com/red-data-tools/charty/blob/cd467e60950b808c758ba545f70589f18cc3896c/charty.gemspec#L19

![image](https://user-images.githubusercontent.com/6506296/64428255-f76ba700-d0bb-11e9-8849-52882742b65c.png)

**Comment by 284km** [comment]
Thanks for reporting.
Hmm, but I still don't know the cause.

**Comment by indigolain** [comment]
This issue may be related? https://github.com/rubygems/rubygems.org/issues/1937
It says here that setting `metadata.homepage_uri` is recommended when you want to specify the links shown in rubygems.

I think you can see how this works by looking [here](https://github.com/rubygems/rubygems.org/blob/a7d0b57fff414223f468de79b6785f38d8b01e3d/app/models/links.rb#L57) that if `metadata.homepage_uri` is set, this value will be used for the links in the rubygems page instead of `linkset&.home`, which is updated by setting  `spec.homepage` and if `version.reload.latest?` is true in [here](https://github.com/rubygems/rubygems.org/blob/1259f97507551e2656949af80818c1d7df362438/app/models/rubygem.rb#L226).

**Comment by 284km** [comment]
Thanks for useful information.

I just released version 0.2.0. Then each link is now displayed correctly and this issue is resolved. but I'm not sure why...

https://rubygems.org/gems/charty

<img width="260" alt="charty_v020" src="https://user-images.githubusercontent.com/1458041/65742436-17c2da80-e12b-11e9-8fe2-4e7069cff825.png">
